
% Previous was, for first two runs (choices, outcomes):
%tapas_fitModel( ...
%	{'Left','Middle','Right'}, ...
%	{'Win','Lose'}, ...
%	'tapas_hgf_ar1_binary_mab_config_1', ...
%	'tapas_softmax_mu3_config' ...
%	);

% For second two runs:
%tapas_fitModel( ...
%	{'Left','Middle','Right'}, ...
%	{'Win','Lose'}, ...
%	'tapas_hgf_ar1_binary_mab_config_2', ...
%	'tapas_softmax_mu3_config' ...
%	);

% Load our eprime trials report
info = readtable('../../OUTPUTS/new/eprime_report.csv');

% Split by "easy" and "hard" based on fmri run
inds1 = ismember(info.Run,[1 2]);
inds2 = ismember(info.Run,[3 4]);

result1 = tapas_fitModel( ...
	info.ChosenProb(inds1), ...
	info.Outcome(inds1), ...
	'tapas_hgf_ar1_binary_mab_config_1', ...
	'tapas_softmax_mu3_config' ...
	);

